"""Dump an instance + both solutions to web/data.js for the offline dashboard.

Writes a single ``window.ROUTEOPT`` object (a JS assignment, not JSON, so the
page loads with no fetch and no server — just open index.html). Run:

    python web/build_data.py --instance data/instances/n60.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))  # repo root, so `routeopt` imports when run directly

from routeopt.heuristic import Solution, clarke_wright  # noqa: E402
from routeopt.model import distance_matrix, load_instance  # noqa: E402
from routeopt.solver import solve_cvrp  # noqa: E402


def _solution_dict(sol: Solution) -> dict:
    return {
        "method": sol.method,
        "routes": sol.routes,
        "total_distance": round(sol.total_distance, 2),
        "vehicles_used": sol.vehicles_used,
        "loads": sol.loads,
        "feasible": sol.feasible,
        "solve_time_s": round(sol.solve_time_s, 3),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--instance", type=Path, default=Path("data/instances/n60.json"))
    ap.add_argument("--time-limit", type=int, default=8)
    args = ap.parse_args(argv)

    instance = load_instance(args.instance)
    dist = distance_matrix(instance)
    ort = solve_cvrp(instance, time_limit_s=args.time_limit)
    cw = clarke_wright(instance, dist)

    payload = {
        "instance": {
            "name": instance.name,
            "depot": instance.depot,
            "capacity": instance.capacity,
            "num_vehicles": instance.num_vehicles,
            "num_customers": instance.num_customers,
            "total_demand": instance.total_demand,
            "coords": instance.coords.tolist(),
            "demands": instance.demands.tolist(),
        },
        "or_tools": _solution_dict(ort),
        "clarke_wright": _solution_dict(cw),
    }

    out = HERE / "data.js"
    out.write_text(
        "// Auto-generated by web/build_data.py — do not edit by hand.\n"
        "window.ROUTEOPT = " + json.dumps(payload, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(
        f"wrote {out}  ({instance.name}: OR-Tools {ort.total_distance:.1f} / "
        f"savings {cw.total_distance:.1f})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
